# -*- coding: utf-8 -*-
# NUS-WIDE config adapted from the original COCO LT_resnet50_pfc_DB.py.
#
# IMPORTANT:
# 1) This is a template for NUS-WIDE.
# 2) The original config uses COCO-style dataset loading (CocoDataset + ann_file json).
# 3) To run this directly, your `mllt` codebase must already support a NUS-WIDE dataset
#    class compatible with the fields below, e.g. `NUSWideDataset`.
# 4) If your current training path uses the text files generated by
#    create_nw_pmlt_from_csv.py (nw_lt_train.txt / nw_lt_test.txt / nw_labels.txt),
#    you may still need to add the corresponding dataset class in `mllt.datasets`.

# model settings
model = dict(
    type='SimpleClassifier',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='PFC',
        in_channels=2048,
        out_channels=256,
        dropout=0.5),
    head=dict(
        type='ClsHead',
        in_channels=256,
        num_classes=81,
        method='fc',
        loss_cls=dict(
            type='ResampleLoss',
            use_sigmoid=True,
            reweight_func='rebalance',
            focal=dict(focal=True, balance_param=2.0, gamma=2),
            logit_reg=dict(neg_scale=2.0, init_bias=0.05),
            map_param=dict(alpha=0.1, beta=10.0, gamma=0.2),
            loss_weight=1.0,
            # TODO: replace with your real class frequency file if required by your ResampleLoss
            # Example generated/expected location:
            freq_file='../appendix/nuswide/class_freq.pkl'
        )))

# model training and testing settings
train_cfg = dict()
test_cfg = dict()

# dataset settings
dataset_type = 'NUSWideDataset'
data_root = '../data/nuswide/'
online_data_root = '../appendix/nuswide/'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)

extra_aug = dict(
    photo_metric_distortion=dict(
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    random_crop=dict(
        min_crop_size=0.8))

img_size = 224

# NOTE:
# The original COCO config uses:
#   ann_file = instances_train2017.json / instances_val2017.json
# For NUS-WIDE, replace `ann_file` with the annotation / split source required by
# your dataset implementation inside mllt.
#
# If your NUS dataset class is written to consume the text files generated by
# create_nw_pmlt_from_csv.py, you can point the fields below to those files.

data = dict(
    imgs_per_gpu=16,
    workers_per_gpu=1,
    sampler='ClassAware',
    train=dict(
        type=dataset_type,
        # TODO: replace with the actual training annotation file expected by your NUS dataset class
        ann_file=online_data_root + 'nw_lt_train.txt',
        # keep the LT split file for consistency with the original long-tail pipeline
        LT_ann_file=[online_data_root + 'img_id.pkl'],
        # TODO: image prefix or root expected by your dataset class
        img_prefix=data_root,
        img_scale=(img_size, img_size),
        img_norm_cfg=img_norm_cfg,
        extra_aug=extra_aug,
        size_divisor=16,
        resize_keep_ratio=False,
        flip_ratio=0.5),
    val=dict(
        type=dataset_type,
        # TODO: replace with the actual validation annotation file expected by your NUS dataset class
        ann_file=online_data_root + 'nw_lt_test.txt',
        img_prefix=data_root,
        img_scale=(img_size, img_size),
        img_norm_cfg=img_norm_cfg,
        size_divisor=16,
        resize_keep_ratio=False,
        flip_ratio=0),
    test=dict(
        type=dataset_type,
        # TODO: replace with the actual test annotation file expected by your NUS dataset class
        ann_file=online_data_root + 'nw_lt_test.txt',
        class_split=online_data_root + 'class_split.pkl',
        img_prefix=data_root,
        img_scale=(img_size, img_size),
        img_norm_cfg=img_norm_cfg,
        size_divisor=16,
        resize_keep_ratio=False,
        flip_ratio=0))

# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))

# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[5, 7])

checkpoint_config = dict(interval=8)

log_config = dict(
    interval=500,
    hooks=[
        dict(type='TextLoggerHook'),
    ])

evaluation = dict(interval=5)

# runtime settings
start_epoch = 0
total_epochs = 8
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/LT_nuswide_resnet50_pfc_DB'
load_from = None

if start_epoch > 0:
    resume_from = work_dir + '/epoch_{}.pth'.format(start_epoch)
    print("start from epoch {}".format(start_epoch))
else:
    resume_from = None

workflow = [('train', 1)]
